apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: konfig-manager
  name: konfig-manager-metrics-service
  namespace: konfig-manager
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    control-plane: konfig-manager
