# permissions for end users to view hierarchyconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hierarchyconfig-viewer-role
rules:
- apiGroups:
  - konfigmanager.flanksource.com
  resources:
  - hierarchyconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - konfigmanager.flanksource.com
  resources:
  - hierarchyconfigs/status
  verbs:
  - get
