
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: konfig-manager
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - '*'
- apiGroups:
  - konfigmanager.flanksource.com
  resources:
  - konfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - konfigmanager.flanksource.com
  resources:
  - konfigs/finalizers
  verbs:
  - update
- apiGroups:
  - konfigmanager.flanksource.com
  resources:
  - konfigs/status
  verbs:
  - get
  - patch
  - update
