hierarchy:
  - name: "spring-defaults-{{.name}}"
    namespace: default
    kind: ConfigMap
  - name: temp
    namespace: default
    kind: ConfigMap
  - name: sample
    namespace: default
    kind: ConfigMap
    type: propeties
    key: application.properties
  - name: test
    namespace: default
    kind: Secret