package pkg

import "k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"

type Input struct {
	// list of environments where config can be applied
	Environments []string
	// list of services of items being templated.
	Applications []string
	// Resources that are generated by Kustomize
	Resources []Resource
	// The hierarchy in which configs are imported
	Config Config
}
type Resource struct {
	// path is the relative path to the file containing the resource definition
	Path string
	// A configmap, secret or sealed secret
	Item *unstructured.Unstructured
}

type Config struct {
	Hierarchy []Item
}

type Item struct {
	Kind      string
	Name      string
	Namespace string
	Type      string
	Key       string
}
