name: Lint
on:
  push:
    branches:
      - master
      - main
  pull_request:
    paths:
      - '**.go'
      - 'Makefile'
      - '**.jsx?'
      - '**.tsx?'
      - '**/.babelrc'
      - '**/.eslint*'
      - '**/package.json'
      - '**.md'
      - '**/.markdownlint.*'
      - '**/github/workflows/lint.yml'
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
  eslint:
    runs-on: ubuntu-latest
    container:
      image: node:15.14-alpine
    steps:
      - uses: actions/checkout@master
      - run: npm ci
        working-directory: ./ui
      - run: npm run lint:eslint
        working-directory: ./ui
  markdown:
    runs-on: ubuntu-latest
    container:
      image: node:15.14-alpine
    steps:
      - uses: actions/checkout@master
      - run: apk upgrade && apk add --no-cache make bash
      - run: make lint-markdown