name: Create Release
on:
  push:
    branches:
      - main
jobs:
  binary:
    runs-on: ubuntu-latest
    container:
      image: flanksource/build-tools:v0.13.6
    steps:
      - uses: actions/checkout@v2
      - run: export
      - run: make release
      - uses: actions/upload-artifact@v2
        with:
          name: konfig-manager
          path: ./.bin/*

  semantic-release:
    needs: binary
    runs-on: ubuntu-latest
    outputs:
      release-version: ${{ steps.semantic.outputs.release-version }}
      new-release-published: ${{ steps.semantic.outputs.new-release-published }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: konfig-manager
          path: ./.bin
      - uses: codfish/semantic-release-action@v1
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docker:
    needs: semantic-release
    # Only build/push new docker images when there is new version released
    if: needs.semantic-release.outputs.new-release-published == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: flanksource/konfig-manager
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          snapshot: true
          tags: "latest,v${{ needs.semantic-release.outputs.release-version }}"
